// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  frontend: [
    {
      type: "autogenerated",
      dirName: "frontend",
    },
  ],
  algorithm: [
    {
      type: "autogenerated",
      dirName: "algorithm",
    },
  ],
  tools: [
    {
      type: "autogenerated",
      dirName: "tools",
    },
  ],
};

module.exports = sidebars;
